name: "Update Web Site"
on:
  release:
    types:
      - created
      - published
      - edited
      - deleted

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.DEPLOY_PAGE }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'trucaption',
              repo: 'trucaption-pages',
              workflow_id: 'pages-deploy.yml',
              ref: 'main'
            })
